### ISSUE TITLE
(opt) Add Basic Authentication support for HTTP control endpoints

### ISSUE THREAD

**Issue by hashmap-kz** [hashmap-kz/pgrwl#25]
Something like this: 
```
main:
  listen_port: 7070
  directory: "/var/lib/pgwal"
  basic_auth:
    enable: true
    username: admin
    password: ${PGRWL_HTTP_PASSWORD} 
```
